# Generated by Django 6.0.4 on 2026-06-04 10:12

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.files.models.file_directory_path)),
                ('name', models.CharField(max_length=100)),
                ('owner_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vizible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файли',
                'db_table': 'file',
                'ordering': ['-id'],
            },
        ),
    ]
