# Generated by Django 6.0.7 on 2026-08-09 16:43

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=apps.files.models.UploadToPath("file"),
                        verbose_name="Шлях до файлу",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.files.models.UploadToPath("thumbnail"),
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("name", models.CharField(max_length=100, verbose_name="Ім'я файлу")),
                (
                    "owner_id",
                    models.PositiveIntegerField(verbose_name="Айді власника(юзера)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "visible",
                    models.BooleanField(default=True, verbose_name="Видимість"),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файли",
                "db_table": "file",
                "ordering": ["-id"],
            },
        ),
    ]
