# Generated by Django 6.0.4 on 2026-06-05 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filemodel',
            old_name='vizible',
            new_name='visible',
        ),
    ]
