# Generated by Django 6.0.4 on 2026-06-11 10:35

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_rename_vizible_filemodel_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата створення'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=apps.files.models.file_directory_path, verbose_name='Шлях до файлу'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='name',
            field=models.CharField(max_length=100, verbose_name="Ім'я файлу"),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='owner_id',
            field=models.PositiveIntegerField(verbose_name='Айді власника(юзера)'),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='visible',
            field=models.BooleanField(default=True, verbose_name='Видимість'),
        ),
    ]
