# Generated by Django 6.0.7 on 2026-08-02 12:09

import apps.files.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_alter_filemodel_created_at_alter_filemodel_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='is_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='medium',
            field=models.ImageField(blank=True, null=True, upload_to=apps.files.models.UploadToPath('medium')),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.files.models.UploadToPath('thumbnail')),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='file',
            field=models.FileField(upload_to=apps.files.models.UploadToPath('file'), verbose_name='Шлях до файлу'),
        ),
    ]
