# Generated by Django 6.0.7 on 2026-08-03 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_filemodel_is_processed_filemodel_medium_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='medium',
        ),
    ]
