

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ukr-forum-backend:dev
    command: sh -c "python manage.py runserver 0.0.0.0:$${PORT}"
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - django_logs:/app/logs
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ukr-forum-frontend:dev

    ports:
      - "5173:5173"

    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

  db:
    image: postgres:18.4-trixie
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql

  redis:
    image: redis:8.10.0-trixie
    container_name: redis
    restart: unless-stopped

    volumes:
      - redis-data:/data

    command: >
      redis-server
      --appendonly yes
      --save 60 1000

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: ./backend
    entrypoint: []
    container_name: celery
    restart: unless-stopped
    command: celery -A config worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - django_logs:/app/logs

  celery-beat:
    build:
      context: ./backend
    entrypoint: []
    container_name: celery-beat
    restart: unless-stopped
    command: celery -A config beat --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - django_logs:/app/logs

  loki:
    image: grafana/loki:3.7.3
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data:/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:3.6.10
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:13.0.3
    ports:
      - "3000:3000"
    env_file:
      - backend/.env
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki

volumes:
  db-data:
  loki_data:
  grafana_data:
  django_logs:
  redis-data: