

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ukr-forum-backend:dev
    command: sh -c "python manage.py runserver 0.0.0.0:$${PORT}"
    ports:
      - "8080:8080"
    env_file:
      - backend/.env
    volumes:
      - ./backend:/app
      - django_logs-dev:/app/logs
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: ukr-forum-frontend:dev

    ports:
      - "5173:5173"

    environment:
      BACKEND_HOST: backend
      BACKEND_PORT: 8080

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend

  db:
    image: postgres:18.4-trixie
    ports:
      - "5433:5432"
    env_file:
      - backend/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db-data-dev:/var/lib/postgresql

  redis:
    build: ./redis

    volumes:
      - redis-data-dev:/data
      - ./redis/redis.conf.template:/usr/local/etc/redis/redis.conf.template

    env_file:
      - ./redis/.env

    healthcheck:
      test: ["CMD-SHELL", "redis-cli --user app_user -a $$REDIS_USER_PASSWORD ping | grep -q PONG"]
      interval: 10s
      timeout: 5s
      retries: 5

  celery:
    build:
      context: ./backend
    entrypoint: []
    container_name: celery
    restart: unless-stopped
    command: celery -A config worker --loglevel=info
    env_file:
      - ./backend/.env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    volumes:
      - ./backend:/app
      - django_logs-dev:/app/logs

  # celery-beat:
  #   build:
  #     context: ./backend
  #   entrypoint: []
  #   container_name: celery-beat
  #   restart: unless-stopped
  #   command: celery -A config beat --loglevel=info
  #   env_file:
  #     - ./backend/.env
  #   depends_on:
  #     redis:
  #       condition: service_started
  #   volumes:
  #     - /app
  #     - django_logs:/app/logs

  loki:
    image: grafana/loki:3.7.3
    ports:
      - "3100:3100"
    volumes:
      - ./monitoring/loki/loki-config.yaml:/etc/loki/loki-config.yaml:ro
      - loki_data-dev:/loki
    command: -config.file=/etc/loki/loki-config.yaml

  promtail:
    image: grafana/promtail:3.6.10
    container_name: promtail
    restart: unless-stopped
    volumes:
      - ./monitoring/promtail/promtail-config.yaml:/etc/promtail/config.yaml:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    command: -config.file=/etc/promtail/config.yaml
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:13.0.3
    ports:
      - "3000:3000"
    env_file:
      - ./monitoring/.env
    volumes:
      - grafana_data-dev:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - loki

volumes:
  db-data-dev:
  loki_data-dev:
  grafana_data-dev:
  django_logs-dev:
  redis-data-dev: