from collections.abc import Iterator
from typing import Protocol, runtime_checkable


@runtime_checkable
class UploadedFileLike(Protocol):
    @property
    def name(self) -> str: ...
    @property
    def content_type(self) -> str | None: ...
    @property
    def size(self) -> int: ...

    def read(self, size: int = -1) -> bytes: ...
    def seek(self, offset: int, whence: int = 0) -> int: ...
    def chunks(self, chunk_size: int | None = None) -> Iterator[bytes]: ...
