# Generated by Django 6.0.7 on 2026-08-09 16:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='viewer', verbose_name='Роль користувача')),
                ('name_ua', models.CharField(blank=True, default='', verbose_name='Роль користувача українською')),
                ('is_bool', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True, verbose_name='Код')),
                ('name', models.CharField(max_length=20, verbose_name='Назва')),
            ],
            options={
                'verbose_name': 'Одиниця вимірювання',
                'verbose_name_plural': 'Одиниці вимірювання',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорій')),
                ('icon', models.CharField(blank=True, default='', max_length=10, verbose_name='Іконка (emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='household.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'household_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва групи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'db_table': 'household_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(blank=True, null=True, verbose_name='ID країни')),
                ('region_id', models.IntegerField(blank=True, null=True, verbose_name='ID регіону')),
                ('city_id', models.IntegerField(blank=True, null=True, verbose_name='ID міста')),
                ('name', models.CharField(max_length=100, verbose_name='Назва активу')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса(вул.+дім)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='household.group', verbose_name='Група')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активи',
                'db_table': 'household_asset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(blank=True, null=True, verbose_name='ID країни')),
                ('region_id', models.IntegerField(blank=True, null=True, verbose_name='ID регіону')),
                ('city_id', models.IntegerField(blank=True, null=True, verbose_name='ID міста')),
                ('name', models.CharField(max_length=150, verbose_name='Магазин')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса(вул.+дім)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
                'db_table': 'household_market',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Найменування товару')),
                ('create_date', models.DateField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cat_products', to='household.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit_of_measure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unit_products', to='household.unitofmeasure')),
            ],
            options={
                'verbose_name': 'Товар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_purchase', models.DateField(verbose_name='Дата покупки')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='household.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.market', verbose_name='Магазин')),
            ],
            options={
                'db_table': 'household_purchase',
                'ordering': ['-data_purchase'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Доступна кількість', max_digits=12, verbose_name='Кількість')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Ціна за 1 шт/кг/л', max_digits=12, verbose_name='Ціна за одиницю')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='household.purchase')),
            ],
            options={
                'db_table': 'household_purchase_item',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приєднання')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='household.group', verbose_name='Група')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.role', verbose_name='Роль')),
            ],
            options={
                'verbose_name': 'Учасник групи',
                'verbose_name_plural': 'Учасники групи',
                'db_table': 'household_group_member',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
