# Generated by Django 6.0.4 on 2026-05-15 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорій')),
                ('icon', models.CharField(blank=True, default='', max_length=10, verbose_name='Іконка (emoji)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='household.category', verbose_name='Батьківська категорія')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'db_table': 'household_category',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва групи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Створив')),
            ],
            options={
                'verbose_name': 'Група',
                'verbose_name_plural': 'Групи',
                'db_table': 'household_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва типу')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='place_types', to='household.group', verbose_name='Група')),
            ],
            options={
                'verbose_name': "Тип об'єкта",
                'verbose_name_plural': "Типи об'єктів",
                'db_table': 'household_place_type',
                'ordering': ['name'],
                'unique_together': {('name', 'group')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва активу')),
                ('country_id', models.IntegerField(blank=True, null=True, verbose_name='ID країни')),
                ('region_id', models.IntegerField(blank=True, null=True, verbose_name='ID регіону')),
                ('city_id', models.IntegerField(blank=True, null=True, verbose_name='ID міста')),
                ('address', models.CharField(blank=True, default='', max_length=255, verbose_name='Адреса (вулиця, дім)')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='household.group', verbose_name='Група')),
                ('place_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='household.placetype', verbose_name='Тип місця')),
            ],
            options={
                'verbose_name': 'Актив',
                'verbose_name_plural': 'Активи',
                'db_table': 'household_asset',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('creator', 'Власник'), ('editor', 'Редактор'), ('viewer', 'Глядач')], default='viewer', max_length=10, verbose_name='Роль')),
                ('joined_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата приєднання')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='household.group', verbose_name='Група')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL, verbose_name='Користувач')),
            ],
            options={
                'verbose_name': 'Учасник групи',
                'verbose_name_plural': 'Учасники групи',
                'db_table': 'household_group_member',
                'unique_together': {('group', 'user')},
            },
        ),
    ]
