# Generated by Django 6.0.4 on 2026-05-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='address',
        ),
        migrations.AddField(
            model_name='asset',
            name='address_line',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса(вул.+дім)'),
        ),
    ]
