# Generated by Django 6.0.4 on 2026-05-15 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_remove_asset_address_asset_address_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Найменування товару')),
                ('unit_of_measure', models.CharField(choices=[('шт', 'Штуки (шт)'), ('кг', 'Кілограми (кг)'), ('г', 'Грами (г)'), ('л', 'Літри (л)'), ('мл', 'Мілілітри (мл)'), ('м', 'Метри (м)'), ('уп', 'Упаковка (уп)'), ('кор', 'Коробка (кор)')], default='шт', help_text='В якій одиниці продається товар', max_length=10, verbose_name='Одиниця вимірювання')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Доступна кількість', max_digits=12, verbose_name='Кількість')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Ціна за 1 шт/кг/л', max_digits=12, verbose_name='Ціна за одиницю')),
                ('price', models.DecimalField(blank=True, decimal_places=2, help_text='Ціна за всю наявну кількість (автоматично?)', max_digits=12, null=True, verbose_name='Загальна ціна')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['name'],
            },
        ),
    ]
