# Generated by Django 6.0.4 on 2026-05-15 18:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_id', models.IntegerField(blank=True, null=True, verbose_name='ID країни')),
                ('region_id', models.IntegerField(blank=True, null=True, verbose_name='ID регіону')),
                ('city_id', models.IntegerField(blank=True, null=True, verbose_name='ID міста')),
                ('name', models.CharField(max_length=150, verbose_name='Магазин')),
                ('address_line', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адреса(вул.+дім)')),
            ],
            options={
                'verbose_name': 'Магазин',
                'verbose_name_plural': 'Магазини',
                'db_table': 'market',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='asset',
            name='place_type',
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Товар'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price_per_unit',
        ),
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='household.category'),
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_purchase', models.DateField(verbose_name='Дата покупки')),
                ('note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='household.asset')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('market', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.market', verbose_name='Магазин')),
            ],
            options={
                'db_table': 'household_purchase',
                'ordering': ['-data_purchase'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(blank=True, default='', help_text='Зберігається автоматично при збереженні рядка чеку', max_length=150, verbose_name='Назва товару')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, help_text='Доступна кількість', max_digits=12, verbose_name='Кількість')),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Ціна за 1 шт/кг/л', max_digits=12, verbose_name='Ціна за одиницю')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='household.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='household.purchase')),
            ],
            options={
                'db_table': 'household_purchase_item',
            },
        ),
        migrations.DeleteModel(
            name='PlaceType',
        ),
    ]
