# Generated by Django 6.0.4 on 2026-07-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0009_product_create_date_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseitem',
            name='product_name_snapshot',
        ),
    ]
