# Generated by Django 6.0.4 on 2026-07-11 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0010_remove_purchaseitem_product_name_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='viewer', verbose_name='Роль користувача')),
                ('name_ua', models.CharField(blank=True, default='', verbose_name='Роль користувача українською')),
                ('is_bool', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='groupmember',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.role', verbose_name='Роль'),
        ),
    ]
