from typing import Protocol

from core.dto.users.user_dto import UserShortOutDTO,UserPublicOutDTO


class UserProtocol(Protocol):
    def get(self, user_id: int) -> UserPublicOutDTO | None: ...
    def get_many(self, ids: list[int]) -> dict[int,UserPublicOutDTO]: ...


class UserShortProtocol(Protocol):
    def get(self, user_id: int) -> UserShortOutDTO | None: ...
    def get_many(self, ids: list[int]) -> dict[int,UserShortOutDTO]: ...
