from typing import Protocol

from apps.geo.contracts.dto.city_dto import CityDTO


class CityContractProtocol(Protocol):
    def get(self, city_id: int) -> CityDTO: ...
    def get_many(self, city_ids: list[int]) -> dict[int, CityDTO]: ...
    def get_by_region(self, region_id: int) -> dict[int, CityDTO]: ...
