# Generated by Django 6.0.7 on 2026-08-09 16:43

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version",
                    models.CharField(max_length=10, verbose_name="Версія тексту"),
                ),
                ("text", models.TextField(verbose_name="Текст погодження")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name="Дата створення тексту погодження",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "country_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID країни"
                    ),
                ),
                (
                    "region_id",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="ID регіону"
                    ),
                ),
                (
                    "city_id",
                    models.IntegerField(blank=True, null=True, verbose_name="ID міста"),
                ),
                ("country_public", models.BooleanField(default=False)),
                ("region_public", models.BooleanField(default=False)),
                ("city_public", models.BooleanField(default=False)),
                (
                    "username",
                    models.CharField(
                        help_text="Обов'язкове поле. Тільки літери, цифри та @/./+/-/_.",
                        max_length=150,
                        unique=True,
                        verbose_name="Ваш логін",
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=100,
                        verbose_name="Публічне ім'я (нікнейм)",
                    ),
                ),
                ("first_name_public", models.BooleanField(default=False)),
                ("last_name_public", models.BooleanField(default=False)),
                ("age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Телефон"
                    ),
                ),
                ("phone_public", models.BooleanField(default=False)),
                ("email_public", models.BooleanField(default=False)),
                (
                    "social_network",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="Соц.мережа"
                    ),
                ),
                ("social_public", models.BooleanField(default=False)),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False, verbose_name="Згода на обробку даних"
                    ),
                ),
                (
                    "consent_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата згоди"
                    ),
                ),
                ("visibility", models.JSONField(default=dict)),
                ("is_banned", models.BooleanField(default=False)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
                (
                    "consent_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="users.consenttext",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
