# Generated by Django 6.0.7 on 2026-08-01 19:13

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='Версія тексту')),
                ('text', models.TextField(verbose_name='Текст погодження')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення тексту погодження')),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('country_id', models.IntegerField(blank=True, null=True, verbose_name='ID країни')),
                ('region_id', models.IntegerField(blank=True, null=True, verbose_name='ID регіону')),
                ('city_id', models.IntegerField(blank=True, null=True, verbose_name='ID міста')),
                ('country_public', models.BooleanField(default=False)),
                ('region_public', models.BooleanField(default=False)),
                ('city_public', models.BooleanField(default=False)),
                ('username', models.CharField(help_text="Обов'язкове поле. Тільки літери, цифри та @/./+/-/_.", max_length=100, unique=True, verbose_name='Ваш логін')),
                ('display_name', models.CharField(max_length=100, verbose_name="Публічне ім'я")),
                ('first_name_public', models.BooleanField(default=False)),
                ('last_name_public', models.BooleanField(default=False)),
                ('email_public', models.BooleanField(default=False)),
                ('is_email_verified', models.BooleanField(default=False)),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Дата народження')),
                ('date_of_birth_public', models.BooleanField(default=False)),
                ('phone_number', models.CharField(blank=True, max_length=50, verbose_name='Ваш тел.номер')),
                ('phone_public', models.BooleanField(default=False)),
                ('social_network', models.CharField(blank=True, max_length=50, verbose_name='Ваша соц.мережа')),
                ('social_public', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('deletion_scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('consent_given', models.BooleanField(default=False, verbose_name='Погодження')),
                ('consent_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата погодження')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('consent_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.consenttext')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='Одноразовий код скидання')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли створено')),
                ('expires_at', models.DateTimeField(verbose_name='')),
                ('is_used', models.BooleanField(default=False, verbose_name='Використаний/Невикористаний')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому належить токен')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True, verbose_name='унікальний рядок, uuid4')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли створений код')),
                ('expires_at', models.DateTimeField(verbose_name='Кінцева дата використання коду')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активний/неактивний')),
                ('max_uses', models.IntegerField(blank=True, null=True, verbose_name='Ліміт використання коду 1 або безліч')),
                ('used_count', models.IntegerField(default=0, verbose_name='Лічільник використання активного коду')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Власник реф.коду')),
            ],
        ),
        migrations.CreateModel(
            name='ReferralUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли скористалися кодом')),
                ('code', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.referralcode', verbose_name='Код яким скористались')),
                ('used_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, unique=True, verbose_name='Хто скористався')),
            ],
        ),
    ]
