# Generated by Django 6.0.7 on 2026-09-09 23:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='consent_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата погодження'),
        ),
        migrations.CreateModel(
            name='EmailConfirmationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='Одноразовий код підтвердження email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Коли створено')),
                ('expires_at', models.DateTimeField(verbose_name='Коли токен стає недійсним')),
                ('is_used', models.BooleanField(default=False, verbose_name='Використаний/Невикористаний')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Кому належить токен')),
            ],
        ),
    ]
