# Generated by Django 6.0.4 on 2026-04-24 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10, verbose_name='Версія тексту')),
                ('text', models.TextField(verbose_name='Текст погодження')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення тексту погодження')),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата згоди'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_given',
            field=models.BooleanField(default=False, verbose_name='Згода на обробку даних'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name="Публічне ім'я (нікнейм)"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='first_name_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_network',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Соц.мережа'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='social_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customuser',
            name='visibility',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(help_text="Обов'язкове поле. Тільки літери, цифри та @/./+/-/_.", max_length=150, unique=True, verbose_name='Ваш логін'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='consent_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.consenttext'),
        ),
    ]
