# Generated by Django 6.0.4 on 2026-05-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_consenttext_customuser_age_customuser_city_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_city', to='geo.city', verbose_name='Місто'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_country', to='geo.country', verbose_name='Країна'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_region', to='geo.region', verbose_name='Регіон'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city_public',
            field=models.BooleanField(default=False, verbose_name='Міто публічне'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country_public',
            field=models.BooleanField(default=False, verbose_name='Країна публічна'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region_public',
            field=models.BooleanField(default=False, verbose_name='Регіон публічний'),
        ),
    ]
