# Generated by Django 6.0.4 on 2026-05-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_city_customuser_country_customuser_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='city',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='country',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='region',
        ),
        migrations.AddField(
            model_name='customuser',
            name='city_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID міста'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='country_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID країни'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='region_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='ID регіону'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='city_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='country_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='region_public',
            field=models.BooleanField(default=False),
        ),
    ]
