# Generated by Django 6.0.7 on 2026-08-09 16:43

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("search", "0002_enable_pg_trgm"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.CharField(max_length=1500)),
                ("price", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("visible", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("new", "Новий"), ("used", "Б/В")],
                        default="new",
                        max_length=10,
                    ),
                ),
                ("owner_id", models.PositiveIntegerField()),
                ("category_id", models.IntegerField()),
                (
                    "file_ids",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.PositiveIntegerField()
                    ),
                ),
                ("country_id", models.PositiveIntegerField(null=True)),
                ("region_id", models.PositiveIntegerField(null=True)),
                ("city_id", models.PositiveIntegerField(null=True)),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
                "db_table": "product",
                "ordering": ["-id"],
                "indexes": [
                    models.Index(fields=["status"], name="product_status_407ffb_idx"),
                    models.Index(
                        fields=["category_id"], name="product_categor_26b384_idx"
                    ),
                    models.Index(
                        fields=["country_id"], name="product_country_336af1_idx"
                    ),
                    models.Index(
                        fields=["region_id"], name="product_region__dd18dd_idx"
                    ),
                    models.Index(fields=["city_id"], name="product_city_id_1a24aa_idx"),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.search.SearchVector(
                            "title", "description", config="simple"
                        ),
                        name="shop_product_search_gin",
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        django.contrib.postgres.indexes.OpClass(
                            "description", name="gin_trgm_ops"
                        ),
                        name="description_trgm_idx",
                    ),
                ],
            },
        ),
    ]
