# Generated by Django 6.0.7 on 2026-08-09 15:21

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.CharField(max_length=1500)),
                ('price', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'Новий'), ('used', 'Б/В')], default='new', max_length=10)),
                ('owner_id', models.PositiveIntegerField()),
                ('category_id', models.IntegerField()),
                ('file_ids', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField())),
                ('country_id', models.PositiveIntegerField(null=True)),
                ('region_id', models.PositiveIntegerField(null=True)),
                ('city_id', models.PositiveIntegerField(null=True)),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'db_table': 'product',
                'ordering': ['-id'],
            },
        ),
    ]
