# Generated by Django 6.0.7 on 2026-08-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='file_ids',
        ),
        migrations.CreateModel(
            name='ProductFileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.PositiveIntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='shop.productmodel', verbose_name='Файли товара')),
            ],
            options={
                'verbose_name': 'Файл товару',
                'verbose_name_plural': 'Файли товарів',
                'db_table': 'file_product',
                'ordering': ['-id'],
                'indexes': [models.Index(fields=['file_id'], name='file_produc_file_id_578a9d_idx')],
                'constraints': [models.UniqueConstraint(fields=('product', 'file_id'), name='uniq_product_file')],
            },
        ),
    ]
