# Generated by Django 6.0.4 on 2026-05-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_alter_productmodel_options_productmodel_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="owner_id",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="vizible",
            field=models.BooleanField(default=True),
        ),
    ]
