# Generated by Django 6.0.4 on 2026-05-18 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_productmodel_owner_id_productmodel_vizible'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='city_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='country_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productmodel',
            name='region_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
