# Generated by Django 6.0.4 on 2026-05-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_productmodel_city_id_productmodel_country_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='city_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='country_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='region_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
