# Generated by Django 6.0.4 on 2026-06-07 13:07

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_productmodel_city_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='vizible',
            new_name='visible',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='files_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField()),
            preserve_default=False,
        ),
    ]
