# Generated by Django 6.0.4 on 2026-06-26 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_rename_vizible_productmodel_visible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
