# Generated by Django 6.0.7 on 2026-07-12 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_productmodel_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodel',
            old_name='files_ids',
            new_name='file_ids',
        ),
    ]
