# Generated by Django 6.0.7 on 2026-07-18 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_files_ids_productmodel_file_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.CharField(choices=[('new', 'Новий'), ('used', 'Б/В')], default='new', max_length=10),
        ),
    ]
