# Generated by Django 6.0.7 on 2026-08-01 13:11

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productmodel_status'),
        ("search", "0003_enable_pg_trgm"),
    ]

    operations = [
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['status'], name='product_status_407ffb_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['category_id'], name='product_categor_26b384_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['country_id'], name='product_country_336af1_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['region_id'], name='product_region__dd18dd_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=models.Index(fields=['city_id'], name='product_city_id_1a24aa_idx'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('title', 'description', config="simple"), name='shop_product_search_gin'),
        ),
        migrations.AddIndex(
            model_name='productmodel',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass('description', name='gin_trgm_ops'), name='description_trgm_idx'),
        ),
    ]
