# Generated by Django 6.0.4 on 2026-05-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва країни')),
                ('name_ua', models.CharField(blank=True, default='', max_length=100, verbose_name='Назва українською')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='Код країни')),
                ('flag_emoji', models.CharField(blank=True, max_length=10, verbose_name='Прапор')),
                ('currency', models.CharField(blank=True, max_length=10, null=True, verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Країна',
                'verbose_name_plural': 'Країни',
                'db_table': 'geo_country',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва регіону')),
                ('name_ua', models.CharField(blank=True, default='', max_length=100, verbose_name='Назва українською')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID в Geo API')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='geo.country', verbose_name='Країна')),
            ],
            options={
                'verbose_name': 'Регіон',
                'verbose_name_plural': 'Регіони',
                'db_table': 'geo_region',
                'ordering': ['country__name', 'name'],
                'unique_together': {('name', 'country')},
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Назва міста')),
                ('name_ua', models.CharField(blank=True, default='', max_length=255, verbose_name='Назва українською')),
                ('api_id', models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ID в Geo API')),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=20, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.country', verbose_name='Країна')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geo.region', verbose_name='Регіон')),
            ],
            options={
                'verbose_name': 'Місто',
                'verbose_name_plural': 'Міста',
                'db_table': 'geo_city',
                'ordering': ['country__name', 'region__name', 'name'],
            },
        ),
    ]
