# Generated by Django 6.0.7 on 2026-08-06 17:05

import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("geo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="city", name="country"),
        migrations.RemoveField(model_name="city", name="region"),
        migrations.RenameModel(old_name="Region", new_name="RegionModel"),
        migrations.RenameModel(old_name="Country", new_name="CountryModel"),
        migrations.RenameModel(old_name="City", new_name="CityModel"),
        migrations.AlterField(
            model_name="regionmodel",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="regions",
                to="geo.countrymodel",
                verbose_name="Країна",
            ),
        ),
        migrations.AddField(
            model_name="citymodel",
            name="country",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.countrymodel",
                verbose_name="Країна",
                null=True,
            ),  # null=True временно, если в таблице уже есть строки
        ),
        migrations.AddField(
            model_name="citymodel",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="geo.regionmodel",
                verbose_name="Регіон",
                null=True,
            ),
        ),
        migrations.AlterModelOptions(
            name="countrymodel",
            options={
                "verbose_name": "Країна",
                "verbose_name_plural": "Країни",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="citymodel",
            options={
                "verbose_name": "Місто",
                "verbose_name_plural": "Міста",
                "ordering": ["country__name", "region__name", "name"],
            },
        ),
        migrations.AddIndex(
            model_name="countrymodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"],
                name="country_name_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="countrymodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_ua"],
                name="country_name_ua_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="citymodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name"], name="city_name_trgm_idx", opclasses=["gin_trgm_ops"]
            ),
        ),
        migrations.AddIndex(
            model_name="citymodel",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["name_ua"],
                name="city_name_ua_trgm_idx",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
