from collections.abc import Iterable, Iterator
from typing import Protocol, runtime_checkable

from .dtos import FileRepoDTO


@runtime_checkable
class UploadedFileLike(Protocol):
    @property
    def name(self) -> str: ...
    @property
    def content_type(self) -> str | None: ...
    @property
    def size(self) -> int: ...

    def read(self, size: int = -1) -> bytes: ...
    def seek(self, offset: int, whence: int = 0) -> int: ...
    def chunks(self, chunk_size: int | None = None) -> Iterator[bytes]: ...


class FileRepositoryPort(Protocol):
    def get(self, id: int) -> FileRepoDTO: ...

    def get_many(self, ids: list[int]) -> list[FileRepoDTO]: ...

    def delete(self, id: int) -> tuple[str, str | None]: ...

    def delete_many(self, ids: list[int]) -> tuple[list[str], list[str] | None]: ...

    def create_many(
        self, data: Iterable[UploadedFileLike], user_id: int
    ) -> list[FileRepoDTO]: ...

    def create(self, data, file: UploadedFileLike, user_id: int) -> FileRepoDTO: ...

    def filter_by_id(self, ids: Iterable[int]) -> list[FileRepoDTO]: ...

    def update_files_content(
        self, updates: dict[int, UploadedFileLike]
    ) -> tuple[list[FileRepoDTO], list[str]]: ...
